#  Web scraping and Data cleaning on an E-Commerce Website

### Github has some rendering issue and hence some tables are not properly rendered for this project. I request you to view this projet in NBviewer at [here](https://nbviewer.jupyter.org/github/sreekanthac/Web_Scraping_Amazon/blob/master/Web_Scraping_Amazon.ipynb).

With the evolution of the internet, e-commerce has become so popular that now virtually everyone purchases one or the other product online. With just a few clicks one can have their wish product delivered at their doorstep. In spite of being so convenient, it can be exasperating at times, mainly attributing to the numerous alternatives available on various e-commerce platforms.

Through this project, we are trying to assist one of our customer who wants to purchase a laptop. His hectic work and personal life do not allow him to spend enough time to go through these websites and finalize his purchase. He was in search of support who can help him to finalize on his wish laptop. This brought him to us who gladly accepted this offer.

![e-commerce](e_commerce.png)

[Image source ](https://www.freepik.com/search?dates=any&format=search&page=1&query=online+shopping&sort=popular)

To assist him, we agreed to scrap the data from [amazon](https://www.amazon.com/). We need to do some data cleaning before we can present him with our final list based on his requirements. He can then use this to make his final call. 
In this project, we will be working on web scraping and data cleaning.

The Customer Requirements:
 - Processor : Intel i5 or i7
 - RAM : minimum 8GB 
 - Screen size : between 14 and 16
 - Price limit : upto $1500
 - Good user ratings : 4 and above on 5 star rating system

Now we have all that is needed to start our business, let's begin.

# The Approach

- scraping the required data from an e-commerce website, for this project, it is from amazon.com
- cleaning the data to enable easier analysis
- analyzing the data based on the customer requirements
 
# Initial Setup

We will start with our initial set up where we will import the libraries required for this project.

In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

# Scraping the Data

Here we will scrap relevant information from first the five pages of our search result, which is for laptops from amazon.com as that would give us enough data for our analysis. 
In this step, we are creating a data frame from the scrapped data. We can also create an excel file.

In [14]:
def get_request(pageNo):
    headers = {"User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0", 
               "Accept-Encoding":"gzip, deflate", "Accept":"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
               "DNT":"1","Connection":"close", "Upgrade-Insecure-Requests":"1"}

    req = requests.get('https://www.amazon.com/s?k=laptops&page='+str(pageNo), headers=headers)
    return req
          
def get_content(req):
    return req.content
    
def apply_beautifulsoup(content):
    return BeautifulSoup(content, 'lxml')
    
def get_name(div):
    name_span = div.find('span', attrs={'class':'a-size-medium a-color-base a-text-normal'})
    if name_span is not None:
        return name_span.text
    else:
        return 'no-info'  

def get_price(div):
    price_span = div.find('span', attrs={'class':'a-offscreen'})
    if price_span is not None:
        return price_span.text
    else:
        return 'no-info'
    
def get_rating(div):
    rating_span = div.find('span', attrs={'class':'a-icon-alt'})
    if rating_span is not None:
        return rating_span.text
    else:
        return 'no-info'    
        
all_info = []
for pageNo in range(1,6):
    req = get_request(pageNo)
    content = get_content(req)
    soup = apply_beautifulsoup(content)   
    for d in soup.findAll('div', attrs={'class':'sg-col-4-of-12 sg-col-8-of-16 sg-col-16-of-24 sg-col-12-of-20 sg-col-24-of-32 sg-col sg-col-28-of-36 sg-col-20-of-28'}):
        name = get_name(d)
        price = get_price(d)
        rating = get_rating(d)
        all_info.append([name, price, rating])
        
laptops_info = pd.DataFrame(all_info ,columns=['name', 'price_$', 'ratings'])    
laptops_info

,name,price_$,ratings
0,no-info,no-info,no-info
1,"ASUS VivoBook 15 Thin and Light Laptop, 15.6” ...",$399.99,4.4 out of 5 stars
2,"Lenovo IdeaPad 3 14"" Laptop, 14.0"" FHD (1920 x...",$449.99,3.4 out of 5 stars
3,"Acer Aspire 5 Slim Laptop, 15.6 inches Full HD...",$349.99,4.4 out of 5 stars
4,"ASUS VivoBook 15 Thin and Light Laptop, 15.6” ...",$399.99,4.4 out of 5 stars
...,...,...,...
106,"Dell Latitude E7470 14in Laptop, Core i5-6300U...",$384.00,4.4 out of 5 stars
107,(Renewed) Apple MacBook Pro MD101LL/A 13.3-inc...,no-info,3.6 out of 5 stars
108,Dell Latitude E6420 14.1-Inch Laptop (Intel Co...,no-info,3.8 out of 5 stars
109,XINYANGCH 2019 15.6-inch Laptop 8G + 128G Inte...,$289.00,4.0 out of 5 stars
110,"Lenovo IdeaPad 3 14"" Laptop, 14.0"" FHD (1920 x...",$449.99,3.4 out of 5 stars

# Cleaning the dataset

Before we start analyzing, the dataset needs to be cleaned. Clean data will help us to analyze faster.

In [3]:
# Understading the data types of the dataset
laptops_info.dtypes

name       object
price_$    object
ratings    object
dtype: object

# Cleaning the price column

One of the requirements provided by the customer is the price limit. To make this analysis we need to clean the price column. We will perform the below cleaning operations:
- remove the rows which don't provide price information as the customer is not interested in such options
- remove the '\\$' sign as this information is clear from the column name itself
- convert the column into a numeric type and then round the values which makes it easier for analysis

In [4]:
# Identifying different values in price column
laptops_info['price_$'].value_counts(dropna=False)

no-info    18
$269.99     7
$279.00     6
$289.99     5
$289.00     4
           ..
$493.00     1
$445.00     1
$344.00     1
$359.99     1
$270.00     1
Name: price_$, Length: 61, dtype: int64

In [5]:
# Removing the rows with unknown price
laptops_info = laptops_info[laptops_info['price_$']!='no-info']

# Function to clean the price column
def clean_price(price):
    price = price.replace('$', '')  # Replace the '$' with blank eg: '$1,249.99' to '1,249.99'
    price = price.replace(',', '')  # Replace the ',' with blank eg: '1,249.99' to '1249.99'
    price = pd.to_numeric(price)    # Convert the data type to numeric
    price = price.round()           # Round the values
    return price

# Create a new column with the cleaned price
pd.set_option('mode.chained_assignment',None) # to suppress 'SettingWithCopyWarning' warnings
laptops_info['final_price_$'] = laptops_info['price_$'].apply(clean_price)

# Remove entries where price is less than 100 as these could be accessories
laptops_info = laptops_info[laptops_info['final_price_$']>=100]
laptops_info.head()

,name,price_$,ratings,final_price_$
0,"ASUS VivoBook 15 Thin and Light Laptop, 15.6” ...",$399.99,4.4 out of 5 stars,400.0
1,"Lenovo IdeaPad 3 14"" Laptop, 14.0"" FHD (1920 x...",$449.99,3.4 out of 5 stars,450.0
2,"Acer Aspire 5 Slim Laptop, 15.6 inches Full HD...",$349.99,4.4 out of 5 stars,350.0
3,"BMAX 2 in 1 Convertible Laptop, 11.6"" FHD (192...",$369.00,3.7 out of 5 stars,369.0
4,"2020 HP 14“ Laptop (AMD A9-9425 up to 3.7 GHz,...",$394.99,4.1 out of 5 stars,395.0

# Cleaning the rating column

The customer wishes to invest in a laptop which is quite popular in the market. This can be analyzed using user ratings. The rating column is having values such as 4.5 out of 5 stars. What is important here for our analysis is the value of 4.5. We will perform the below cleaning operations on this column.
- extract only the rating
- convert the column into a numeric type which makes it easier to analyze
- replace unknown rating with 0, since removing this row completely may not be a good idea as the customer in spite having rating being 0 still interested to have a look at it

In [6]:
# Identifying different values in ratings column
laptops_info['ratings'].value_counts(dropna=False)

4.2 out of 5 stars    14
4.4 out of 5 stars    12
4.0 out of 5 stars    10
3.9 out of 5 stars     9
3.8 out of 5 stars     9
3.4 out of 5 stars     8
4.3 out of 5 stars     7
4.1 out of 5 stars     7
5.0 out of 5 stars     5
4.6 out of 5 stars     3
4.5 out of 5 stars     2
3.7 out of 5 stars     2
no-info                1
4.8 out of 5 stars     1
3.5 out of 5 stars     1
2.7 out of 5 stars     1
Name: ratings, dtype: int64

In [7]:
# Function to clean ratings column
def clean_ratings(rating):
    rating = rating.split()
    rating = rating[0]
    if rating == 'no-info':
        rating = 0
    rating = pd.to_numeric(rating) # Convert the data type to numeric
    return rating

# Create a new column with the cleaned ratings
laptops_info['ratings_clean'] = laptops_info['ratings'].apply(clean_ratings)
laptops_info.head()

,name,price_$,ratings,final_price_$,ratings_clean
0,"ASUS VivoBook 15 Thin and Light Laptop, 15.6” ...",$399.99,4.4 out of 5 stars,400.0,4.4
1,"Lenovo IdeaPad 3 14"" Laptop, 14.0"" FHD (1920 x...",$449.99,3.4 out of 5 stars,450.0,3.4
2,"Acer Aspire 5 Slim Laptop, 15.6 inches Full HD...",$349.99,4.4 out of 5 stars,350.0,4.4
3,"BMAX 2 in 1 Convertible Laptop, 11.6"" FHD (192...",$369.00,3.7 out of 5 stars,369.0,3.7
4,"2020 HP 14“ Laptop (AMD A9-9425 up to 3.7 GHz,...",$394.99,4.1 out of 5 stars,395.0,4.1

# Extracting more information from the name column

If you remember, our customer's first three requirements were related to technical details. The name column consists of a lot of information about the product along with technical details such as the brand name, screen size, memory, and so on. The first three technical requirements provided by our customer is also hidden in this column. So to make an effective analysis we need to extract these pieces of information. Our next step consists of this process. This is the most complicated part of this project. For extraction, we need to make use of regular expression commonly known as regex.

First, we will extract the processor details and create a new column with this information.

In [8]:
# Extract processor details
reg_processor = r'\b([iI][\d])\b'
laptops_info['processor'] = laptops_info['name'].str.extract(reg_processor)

# Replace 'I5' with #i5'
laptops_info['processor'] = laptops_info['processor'].str.replace('I', 'i')
laptops_info.head()

,name,price_$,ratings,final_price_$,ratings_clean,processor
0,"ASUS VivoBook 15 Thin and Light Laptop, 15.6” ...",$399.99,4.4 out of 5 stars,400.0,4.4,i3
1,"Lenovo IdeaPad 3 14"" Laptop, 14.0"" FHD (1920 x...",$449.99,3.4 out of 5 stars,450.0,3.4,NaN
2,"Acer Aspire 5 Slim Laptop, 15.6 inches Full HD...",$349.99,4.4 out of 5 stars,350.0,4.4,NaN
3,"BMAX 2 in 1 Convertible Laptop, 11.6"" FHD (192...",$369.00,3.7 out of 5 stars,369.0,3.7,NaN
4,"2020 HP 14“ Laptop (AMD A9-9425 up to 3.7 GHz,...",$394.99,4.1 out of 5 stars,395.0,4.1,NaN

Next we will extract the RAM details and create a new column with this information.

In [9]:
# Extract RAM details    
reg_RAM = r'\b([\d]+)[GB]+[ ][\+ LlPpDdRrAaMmEeOoYy\d]+\b' # Caputure group is only digits
laptops_info['ram_gb'] = laptops_info['name'].str.extract(reg_RAM)

# Function to clean ram column
def clean_ram(ram):
    ram = pd.to_numeric(ram)
    return ram

laptops_info['ram_gb'] = laptops_info['ram_gb'].apply(clean_ram)
laptops_info.head()

,name,price_$,ratings,final_price_$,ratings_clean,processor,ram_gb
0,"ASUS VivoBook 15 Thin and Light Laptop, 15.6” ...",$399.99,4.4 out of 5 stars,400.0,4.4,i3,8.0
1,"Lenovo IdeaPad 3 14"" Laptop, 14.0"" FHD (1920 x...",$449.99,3.4 out of 5 stars,450.0,3.4,NaN,8.0
2,"Acer Aspire 5 Slim Laptop, 15.6 inches Full HD...",$349.99,4.4 out of 5 stars,350.0,4.4,NaN,4.0
3,"BMAX 2 in 1 Convertible Laptop, 11.6"" FHD (192...",$369.00,3.7 out of 5 stars,369.0,3.7,NaN,8.0
4,"2020 HP 14“ Laptop (AMD A9-9425 up to 3.7 GHz,...",$394.99,4.1 out of 5 stars,395.0,4.1,NaN,4.0

Finally we will extract the screen size details and create a new column with this information.

In [10]:
# Extract screen size details
reg_screen = r'\b([1][\d]+[\.IiNnCcHh\d]*)[ \d]*\b' # Caputure group is only digits
laptops_info['screen_size_inches'] = laptops_info['name'].str.extract(reg_screen)
# laptops_info['screen_size_inches'].value_counts()
# Function to clean screen size column
def clean_screen_size(size):
    size = size.replace('inch', '')
    size = size.replace('in', '')
    size = pd.to_numeric(size)
    return size

laptops_info['screen_size_inches'] = laptops_info['screen_size_inches'].apply(clean_screen_size)
laptops_info['screen_size_inches'].value_counts()

14.0      27
15.6      25
15.0      12
11.6      10
14.1       5
10.0       4
17.3       3
13.0       3
10.1       1
1660.0     1
17.0       1
Name: screen_size_inches, dtype: int64

# Final Analysis

We are now done with our crucial part of this project which consists of collecting data and cleaning them. We are ready to go ahead with our analysis. Before we begin with our final analysis we will have a look at our customer requirements once again.

The Customer Requirements:
 - Processor : Intel i5 or i7
 - RAM : minimum 8GB 
 - Screen size : between 14 and 16
 - Price limit : upto $1500
 - Good user ratings : 4 and above on 5 star rating system
 
Let's now filter our dataset based on the customer requirements to create the final dataset.

In [12]:
# Columns for the final dataset
columns_final = ['name', 'final_price_$', 'ratings_clean', 'processor', 'ram_gb', 'screen_size_inches']

# Filter dictionary with the customer requirements. This enables easy modification of the requirements
filters = {'processor':{'min':'i5', 'max':'i7'}, 'ram':8, 'price':1500, 'screen':{'min':14, 'max':16}, 'ratings':4}

# Conditions to filter the processor
laptops_final = laptops_info[columns_final][(laptops_info['processor']==filters['processor']['min']) | (laptops_info['processor']==filters['processor']['max'])].copy()

# Conditions to filter the ram and price
laptops_final = laptops_final[(laptops_final['ram_gb']>=filters['ram']) & (laptops_final['final_price_$']<=filters['price'])]

# Conditions to filter the screen size
laptops_final = laptops_final[(laptops_final['screen_size_inches']>=filters['screen']['min']) & (laptops_final['screen_size_inches']<=filters['screen']['max'])]

# Condition to filter the rating
laptops_final = laptops_final[laptops_final['ratings_clean']>=filters['ratings']]
laptops_final

,name,final_price_$,ratings_clean,processor,ram_gb,screen_size_inches
5,"Acer Spin 3 Convertible Laptop, 14 inches Full...",800.0,4.3,i7,16.0,14.0
8,"Acer Aspire 5 Slim Laptop, 15.6"" Full HD IPS D...",580.0,4.4,i5,8.0,15.6
16,"2020 HP 15 15.6"" HD Touchscreen Premium Laptop...",730.0,4.2,i5,16.0,15.0
24,"2020 HP 15 15.6"" HD Touchscreen Premium Laptop...",730.0,4.2,i5,16.0,15.0
28,"New ! Dell Inspiron i3583 15.6"" HD Touch-Scree...",597.0,4.4,i5,8.0,15.6
31,"Lenovo Ideapad L340 Gaming Laptop, 15.6 Inch F...",859.0,4.4,i5,8.0,15.6
35,"2020 HP 15.6"" HD Touchscreen Premium Home & Bu...",665.0,4.5,i5,8.0,15.6
38,"2020 HP 15.6"" Touchscreen Laptop Computer/ 10t...",669.0,4.4,i5,8.0,15.6
43,"Acer Aspire 5 Slim Laptop, 15.6"" Full HD IPS D...",580.0,4.4,i5,8.0,15.6
74,"New HP Pavilion 2-in-1 15.6"" HD Touchscreen La...",685.0,4.3,i5,8.0,15.6
96,"HP High Performance Pavilion 15-cs3073cl 15.6""...",874.0,4.0,i7,16.0,15.0

# Conclusion

After our analysis as per the customer requirements, we created a final dataset that consists of very few selections. Now we can hand over our customer this final dataset that would help him finalize his purchase.

In this project, we applied a generic approach on amazon.com which can also be applied to other similar platforms by analyzing it's page layouts. We can also increase the number of pages we need to scrap which in this case was limited to 5. The platform itself gives more options to filter. But the idea of this project was to understand how to perform web scraping, data cleaning, and analyzing. 

I hope you enjoyed this project.

Thank you!